### ISSUE TITLE
Goal set-up fails with Maven 3.1.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cstroe/fitnesse-launcher-maven-plugin#26]
```
Running fitnesse-launcher-maven-plugin:1.3.0:set-up fails with

[ERROR] Failed to execute goal 
uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up 
(fitnesse-tests) on project fitnesse-integration-test: Execution fitnesse-tests 
of goal uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up 
failed: An API incompatibility was encountered while executing 
uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up: 
java.lang.NoSuchMethodError: 
org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aeth
er/RepositorySystemSession;

Maven 3.1.1
Mac OS X 10.8.5
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)

It works with maven 3.0.4.
```

Original issue reported on code.google.com by `daniel.m...@gmail.com` on 19 Nov 2013 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
The patch supplied for issue 21 
(https://code.google.com/p/fitnesse-launcher-maven-plugin/issues/detail?id=21) 
solves this problem.
```

Original comment by `bjorn.be...@callistaenterprise.se` on 20 Nov 2013 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
See wiki page MavenCompatibility.
This should now be fixed on trunk, for version 1.4.0
```

Original comment by `stewart@javahelp.co.uk` on 8 Jun 2014 at 10:51
- Changed state: **Accepted**
- Added labels: **Priority-Critical**, **Release-1.4.0**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `stewart@javahelp.co.uk` on 9 Jun 2014 at 1:59
- Changed state: **Fixed**
